site_name: AWS Observability Best Practices
docs_dir: 'docs/en'
copyright: 'Copyright &copy; Amazon 2022'
site_author: 'AWS'
site_url: 'https://aws-observability.github.io/observability-best-practices/'
repo_name: 'aws-observability/observability-best-practices'
repo_url: 'https://github.com/aws-observability/observability-best-practices'

theme:
  logo: ../images/aws-logo.png
  favicon: ../images/aws-logo.png
  name: material
  font:
    text: ember
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs.sticky

  palette:
    primary: red
    accent: red

nav:
  - Home: index.md
  - Guides:
    - Best practices overview: guides/index.md
    - Choosing a tracing agent: guides/choosing-a-tracing-agent.md
    - EC2 Monitoring: guides/ec2/ec2-monitoring.md 
    - ECS best practices: 
      - AWS Native:
        - Collecting system metrics: guides/containers/aws-native/ecs/best-practices-metrics-collection-1.md
        - Collecting service metrics: guides/containers/aws-native/ecs/best-practices-metrics-collection-2.md
      - Open Source:
        - Collecting system metrics: guides/containers/oss/ecs/best-practices-metrics-collection-1.md
        - Collecting service metrics: guides/containers/oss/ecs/best-practices-metrics-collection-2.md
    - EKS best practices:
      - AWS Native:
        - CloudWatch Container Insights: guides/containers/aws-native/eks/amazon-cloudwatch-container-insights.md
        - Log aggregation: guides/containers/aws-native/eks/log-aggregation.md
        - API server monitoring: guides/containers/aws-native/eks/eks-api-server-monitoring.md
        - Tracing with X-Ray: guides/containers/aws-native/eks/container-tracing-with-aws-xray.md

    - Operational:
      - ADOT Collector:
        - Operating at scale: guides/operational/adot-at-scale/operating-adot-collector.md
    
    # - APM: guides/apm.md
    # - Containers: guides/containers.md
    # - Dashboards: guides/dashboards.md
    # - Full-stack: guides/full-stack.md
    - Databases:
      - Aurora and RDS: guides/databases/databases.md
    # - Creating an observability strategy: guides/strategy.md
    - Cost optimization:
      - Using Kubecost: guides/cost-optimization/kubecost.md

  - Data types:
    - Logs: signals/logs.md
    - Metrics: signals/metrics.md
    - Traces: signals/traces.md
    - Alarms: signals/alarms.md
    - Events: signals/events.md
    # - Anomalies: signals/anomalies.md

  - Tools:
    - CloudWatch Agent: tools/cloudwatch_agent.md
    # - Amazon Managed Prometheus: tools/amp.md
    - Alarms: tools/alarms.md
    # - Alerting and Incident Management: tools/alerting_and_incident_management.md
    - Dashboards: tools/dashboards.md
    # - Embedded Metric Format: tools/emf.md
    - Internet Monitor: tools/internet_monitor.md
    - Logs: tools/logs.md
    - Metrics: tools/metrics.md
    - Real User Monitoring: tools/rum.md
    - Synthetic Testing: tools/synthetics.md
    # - Tracing with ADOT: tools/adot-traces.md
    - Tracing with AWS X-Ray: tools/xray.md

  - Curated recipes:
    - Recipes: recipes/index.md
    - Dimensions: recipes/dimensions.md
    - Telemetry: recipes/telemetry.md
    - By Compute:
      - recipes/apprunner.md
      - recipes/eks.md
      - recipes/ecs.md
      - recipes/lambda.md
    - By Infra & Databases:
      - Infra: recipes/infra.md
      - Databases:
         - recipes/rds.md
         - recipes/dynamodb.md
         - recipes/msk.md
    - By Language:
      - Java: recipes/java.md
      - Node.js: recipes/nodejs.md
    - By Destination:
      - recipes/cw.md
      - recipes/amp.md
      - recipes/amg.md
      - recipes/aes.md
    - Tasks:
      - Anomaly Detection: recipes/anomaly-detection.md
      - Alerting: recipes/alerting.md
      - Troubleshooting: recipes/troubleshooting.md
      - Workshops: recipes/workshops.md
  - FAQ:
    - General: faq/faq.md
    - AWS X-Ray: faq/x-ray.md
    - Amazon Managed Service for Prometheus: faq/amp.md
    - Amazon Managed Grafana: faq/amg.md
    - AWS Distro for OpenTelemetry: faq/adot.md
    
  - Contributors: contributors.md

# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Français
#       link: /fr/
#       lang: fr

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - footnotes
    - pymdownx.critic    

plugins:
    - search

